# TODO: Missing the prime ministers
# Note -Minister file should be self contained (including gender etc.)
#       as they necessarily havent have been members of parliament.
#      -This however goes against the 5th normal form.
#      -Move individual level data over to individual file.
SELECT ?wiki_id ?wiki_idLabel ?governmentLabel ?roleLabel ?start ?end ?genderLabel ?born ?dead

WHERE
{
  ?government wdt:P31 wd:Q930729.
  ?wiki_id wdt:P31 wd:Q5;
           wdt:P21 ?gender;
           wdt:P569 ?born;
           p:P39 ?pPosition.
  ?pPosition pq:P5054 ?government.

  OPTIONAL {?wiki_id wdt:P570 ?dead }.
  OPTIONAL { ?pPosition ps:P39 ?role }.
  OPTIONAL { ?pPosition pq:P580 ?start }.
  OPTIONAL { ?pPosition pq:P582 ?end }.
   
  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv". }
}
