SELECT DISTINCT ?wiki_id ?start ?end ?roleLabel ?governmentLabel
WHERE
{
    ?wiki_id wdt:P31 wd:Q5;
             p:P39 ?posheld;
    OPTIONAL { ?posheld pq:P580 ?start. }
    OPTIONAL { ?posheld pq:P582 ?end. }

    ?government wdt:P31 wd:Q930729.
    ?posheld pq:P5054 ?government; # Position held in a government
             ps:P39 ?role.
             
  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv". }
}