SELECT DISTINCT ?wiki_id ?roleLabel ?start ?end
WHERE
{
    ?wiki_id wdt:P31 wd:Q5;
             p:P39 ?posheld;
    OPTIONAL { ?posheld pq:P580 ?start. }
    OPTIONAL { ?posheld pq:P582 ?end. }

    VALUES ?role { wd:Q687075 wd:Q105359146 }
    ?posheld ps:P39 ?role. # Position held as a (vice) prime minister

  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv". }
}