SELECT ?wiki_id ?wiki_idLabel ?twitter
WHERE
{
    ?wiki_id p:P39 ?posheld; # With position held
             wdt:P2002 ?twitter.

    # Position held is in one of the chambers
    VALUES ?chamber { wd:Q10655178 wd:Q33071890 wd:Q81531912 }
    ?posheld ps:P39 ?chamber 
             
  SERVICE wikibase:label { bd:serviceParam wikibase:language "sv". }
}